version: 2

# Visit https://goreleaser.com for documentation on how to customize this behavior.
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos: [freebsd, windows, linux, darwin]
    goarch: [amd64, '386', arm, arm64]
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: 'arm64'
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - formats: [zip]                            # v2: plural form
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'  # ok

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    # default cmd is 'gpg'; pass args to use a specific key
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  # draft: true   # uncomment if you want to inspect before publishing

changelog:
  disable: true                               # v2: 'disable', not 'skip'
